export const GET_PODCASTS_REQUEST = 'GET_PODCASTS_REQUEST';
export const GET_PODCASTS_SUCCESS = 'GET_PODCASTS_SUCCESS';

export const GET_PODCAST_REQUEST = 'GET_PODCAST_REQUEST';
export const GET_PODCAST_SUCCESS = 'GET_PODCAST_SUCCESS';
export const GET_PODCAST_FAILURE = 'GET_PODCAST_FAILURE';

export const GET_PODCAST_SUBSCRIPTION_REQUEST = 'GET_PODCAST_SUBSCRIPTION_REQUEST';
export const GET_PODCAST_SUBSCRIPTION_SUCCESS = 'GET_PODCAST_SUBSCRIPTION_SUCCESS';
export const SUBSCRIBE_PODCAST_REQUEST = 'SUBSCRIBE_PODCAST_REQUEST';
export const SUBSCRIBE_PODCAST_SUCCESS = 'SUBSCRIBE_PODCAST_SUCCESS';
export const UNSUBSCRIBE_PODCAST_REQUEST = 'UNSUBSCRIBE_PODCAST_REQUEST';
export const UNSUBSCRIBE_PODCAST_SUCCESS = 'UNSUBSCRIBE_PODCAST_SUCCESS';

export const FETCH_EPISODES_REQUEST = 'FETCH_EPISODES_REQUEST';
export const FETCH_EPISODES_SUCCESS = 'FETCH_EPISODES_SUCCESS';
export const FETCH_EPISODES_FAILURE = 'FETCH_EPISODES_FAILURE';

export const FETCH_EPISODE_REQUEST = 'FETCH_EPISODE_REQUEST';
export const FETCH_EPISODE_SUCCESS = 'FETCH_EPISODE_SUCCESS';
export const PLAY_EPISODE = 'PLAY_EPISODE';

export const SHOW_PLAYER = 'SHOW_PLAYER';
export const PLAY_PLAYER = 'PLAY_PLAYER';
export const PAUSE_PLAYER = 'PAUSE_PLAYER';